from django.urls import reverse

ACCOUNTS_LIST_URL = reverse('all-accounts-list')
ACCOUNT_DETAIL_URL = reverse('all-accounts-detail', kwargs={'pk': 1})

REQUIRED_SUPERUSER_DATA = {
    "username": "superuser",
    "first_name": "Super",
    "last_name": "User",
    "password": "super_user_password"
}

FULL_USER_DATA = {
    "is_superuser": False,
    "username": "eric_johnson",
    "email": "eric_johnson@test.com",
    "is_staff": True,
    "is_active": True,
    "first_name": "Eric",
    "last_name": "Johnson",
    "password": "eric_johnson_password",
    "role": "Manager",
}

ACCOUNTS_FULL_VALID_REAL_DATA = {
    "first_name": "Stephanie",
    "last_name": "Seow",
    "email": "tephanieseow6544@gmail.com",
    "type": "gmail",
    "password": "1C64!u4e18#",
    "recovery_email": "StephanieSeow58@outlook.com",
    "email_forwarding": True,
    "auto_po_seats_scouts": True,
    "errors_failed": "NA",
    "tm_created": False,
    "tm_password": "NA",
    "axs_created": True,
    "axs_password": "NA",
    "sg_created": True,
    "sg_password": "NA",
    "tickets_com_created": True,
    "eventbrite": True,
    "etix": True,
    "ticket_web": True,
    "big_tickets": True,
    "amazon": True,
    "secondary_password": "NA",
    "seat_scouts_added": True,
    "seat_scouts_status": True,
    "airfrance": True,
    "team": "NA",
    "specific_team": "NA",
    "forward_to": "NA",
    "forward_email_password": "NA",
    "disabled": True,
    "ld_computer_used": "LD11",
    "created_at": "2022-11-30",
    "last_opened": '2022-12-28',
    "comments": "NA",
    "phone": "NA",
    "tickets_com_password": "NA",
    "password_reset": False,
    "active_tickets_inside": False,
    "migrated_from": "NA",
    "migrated_to": "NA"
}

ACCOUNTS_FULL_VALID_TEST_DATA = {
    "first_name": "Test first name",
    "last_name": "Test last name",
    "email": "test_email@test.com",
    "type": "test",
    "password": "test_password",
    "recovery_email": "test_recovery_email@test.com",
    "email_forwarding": True,
    "auto_po_seats_scouts": True,
    "errors_failed": "NA",
    "tm_created": False,
    "tm_password": "NA",
    "axs_created": True,
    "axs_password": "NA",
    "sg_created": True,
    "sg_password": "NA",
    "tickets_com_created": True,
    "eventbrite": True,
    "etix": True,
    "ticket_web": True,
    "big_tickets": True,
    "amazon": True,
    "secondary_password": "NA",
    "seat_scouts_added": True,
    "seat_scouts_status": True,
    "airfrance": True,
    "team": "NA",
    "specific_team": "NA",
    "forward_to": "NA",
    "forward_email_password": "NA",
    "disabled": True,
    "ld_computer_used": "test_ld_computer",
    "created_at": "1994-09-02",
    "last_opened": "2022-12-28",
    "comments": "NA",
    "created_by": 1,
    "edited_by": 1,
    "phone": "NA",
    "tickets_com_password": "NA",
    "password_reset": False,
    "active_tickets_inside": False,
    "migrated_from": "NA",
    "migrated_to": "NA"
}

ACCOUNTS_FULL_VALID_TEST_DATA_COPY = {
    "first_name": "Test first name",
    "last_name": "Test last name",
    "email": "test_email@test.com",
    "type": "test",
    "password": "test_password",
    "recovery_email": "test_recovery_email@test.com",
    "email_forwarding": True,
    "auto_po_seats_scouts": True,
    "errors_failed": "NA",
    "tm_created": False,
    "tm_password": "NA",
    "axs_created": True,
    "axs_password": "NA",
    "sg_created": True,
    "sg_password": "NA",
    "tickets_com_created": True,
    "eventbrite": True,
    "etix": True,
    "ticket_web": True,
    "big_tickets": True,
    "amazon": True,
    "secondary_password": "NA",
    "seat_scouts_added": True,
    "seat_scouts_status": True,
    "airfrance": True,
    "team": "NA",
    "specific_team": "NA",
    "forward_to": "NA",
    "forward_email_password": "NA",
    "disabled": True,
    "ld_computer_used": "test_ld_computer",
    "created_at": "1994-09-02",
    "last_opened": "2022-12-28",
    "comments": "NA",
    "created_by": 1,
    "edited_by": 1,
    "phone": "NA",
    "tickets_com_password": "NA",
    "password_reset": False,
    "active_tickets_inside": False,
    "migrated_from": "NA",
    "migrated_to": "NA"
}
