# Generated by Django 4.1.4 on 2023-01-05 07:03

import apps.cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='active_tickets_inside',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='migrated_from',
            field=models.CharField(default='NA', max_length=100, validators=[apps.cards.validators.any_or_na]),
        ),
        migrations.AddField(
            model_name='accounts',
            name='migrated_to',
            field=models.CharField(default='NA', max_length=100, validators=[apps.cards.validators.any_or_na]),
        ),
        migrations.AddField(
            model_name='accounts',
            name='password_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='phone',
            field=models.CharField(default='NA', max_length=50, validators=[apps.cards.validators.any_or_na]),
        ),
        migrations.AddField(
            model_name='accounts',
            name='tickets_com_password',
            field=models.CharField(default='NA', max_length=50, validators=[apps.cards.validators.any_or_na]),
        ),
    ]
