# Generated by Django 4.1.4 on 2023-01-09 05:59

import apps.cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_active_tickets_inside_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='password_matching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='seat_scouts_password',
            field=models.CharField(default='NA', max_length=32, validators=[apps.cards.validators.any_or_na]),
            preserve_default=False,
        ),
    ]
