# Generated by Django 4.1.4 on 2023-01-10 02:34

import apps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_password_matching_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='airfrance',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='created_by',
            field=models.CharField(default='MATEEN', max_length=32, validators=[apps.validators.any_or_na]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='edited_by',
            field=models.CharField(default='NA', max_length=32, validators=[apps.validators.any_or_na]),
        ),
    ]
