# Generated by Django 4.1.4 on 2023-01-11 00:54

import apps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_accounts_airfrance_alter_accounts_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='tm_address',
            field=models.CharField(default='NA', max_length=255, validators=[apps.validators.any_or_na]),
        ),
    ]
