# Generated by Django 3.2.17 on 2023-03-09 09:51

from django.db import migrations, models

import apps.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230301_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='aeromexico_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='aeromexico_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
        migrations.AddField(
            model_name='accounts',
            name='air_france_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='air_france_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
        migrations.AddField(
            model_name='accounts',
            name='avianca_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='avianca_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
        migrations.AddField(
            model_name='accounts',
            name='china_airlines_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='china_airlines_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
        migrations.AddField(
            model_name='accounts',
            name='delta_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='korean_air_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='korean_air_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='aeromexico_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='aeromexico_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='air_france_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='air_france_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='avianca_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='avianca_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='china_airlines_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='china_airlines_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='delta_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='korean_air_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='korean_air_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
    ]
