# Generated by Django 4.1.2 on 2022-10-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_assigned', models.CharField(max_length=150, unique=True)),
                ('platform', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('parent_card', models.CharField(max_length=150)),
                ('card_number', models.IntegerField(max_length=16)),
                ('expiration_date', models.IntegerField(max_length=4)),
                ('cvv_number', models.IntegerField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_into_tm', models.CharField(choices=[(1, True), (2, False)], default=False, max_length=20)),
                ('added_into_tickets_com', models.CharField(choices=[(1, True), (2, False)], default=False, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_team.employees')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_team.teams')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
