# Generated by Django 4.1.3 on 2022-11-10 02:08

import accounts_team.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_assigned', models.EmailField(db_index=True, max_length=150, null=True, verbose_name='Account')),
                ('platform', models.CharField(max_length=255, null=True, verbose_name='Platform')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Type')),
                ('parent_card', models.CharField(max_length=150, null=True, verbose_name='Parent')),
                ('card_number', models.CharField(max_length=16, validators=[accounts_team.validators.clean_card_number])),
                ('expiration_date', models.CharField(max_length=5, null=True, validators=[accounts_team.validators.clean_expiration_date], verbose_name='Exp.date')),
                ('cvv_number', models.CharField(max_length=3, null=True, validators=[accounts_team.validators.clean_cvv_number], verbose_name='CVV')),
                ('limit', models.CharField(default='0', max_length=20, validators=[accounts_team.validators.clean_limit])),
                ('created_by', models.CharField(max_length=255, null=True, verbose_name='Responsible')),
                ('team', models.CharField(max_length=255, null=True, verbose_name='Team')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('in_tm', models.BooleanField(null=True, verbose_name='tickets.com')),
                ('in_tickets_com', models.BooleanField(null=True, verbose_name='TM')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
                'unique_together': {('account_assigned', 'platform')},
            },
        ),
    ]
