# Generated by Django 4.1.3 on 2022-11-10 02:41

import accounts_team.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_assigned',
            field=models.EmailField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, validators=[accounts_team.validators.clean_card_number]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsible'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='cvv_number',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[accounts_team.validators.clean_cvv_number], verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[accounts_team.validators.clean_expiration_date], verbose_name='Exp.date'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='in_tickets_com',
            field=models.BooleanField(blank=True, null=True, verbose_name='TM'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='in_tm',
            field=models.BooleanField(blank=True, null=True, verbose_name='tickets.com'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='limit',
            field=models.CharField(blank=True, default='0', max_length=20, validators=[accounts_team.validators.clean_limit]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='parent_card',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type'),
        ),
    ]
