# Generated by Django 4.1.2 on 2022-10-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='cvv_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='expiration_date',
            field=models.IntegerField(),
        ),
    ]
