# Generated by Django 4.1.2 on 2022-10-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0002_alter_accounts_card_number_alter_accounts_cvv_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ['name'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterField(
            model_name='accounts',
            name='added_into_tickets_com',
            field=models.CharField(choices=[('1', True), ('2', False)], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='added_into_tm',
            field=models.CharField(choices=[('1', True), ('2', False)], default=False, max_length=20),
        ),
    ]
