# Generated by Django 4.1.3 on 2022-11-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0002_alter_accounts_account_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='in_tickets_com',
            field=models.BooleanField(default=False, verbose_name='TM'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='in_tm',
            field=models.BooleanField(default=False, verbose_name='tickets.com'),
        ),
    ]
