# Generated by Django 4.1.2 on 2022-10-20 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0003_alter_employees_options_alter_teams_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts_team.teams'),
        ),
    ]
