# Generated by Django 4.1.3 on 2022-11-11 09:37

import accounts_team.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0003_alter_accounts_in_tickets_com_alter_accounts_in_tm'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawnsAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_assigned', models.EmailField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Account')),
                ('platform', models.CharField(blank=True, max_length=255, null=True, verbose_name='Platform')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('parent_card', models.CharField(blank=True, max_length=150, null=True, verbose_name='Parent')),
                ('card_number', models.CharField(blank=True, max_length=16, validators=[accounts_team.validators.clean_card_number])),
                ('expiration_date', models.CharField(blank=True, max_length=5, null=True, validators=[accounts_team.validators.clean_expiration_date], verbose_name='Exp.date')),
                ('cvv_number', models.CharField(blank=True, max_length=3, null=True, validators=[accounts_team.validators.clean_cvv_number], verbose_name='CVV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('in_tm', models.BooleanField(default=False, verbose_name='in TM')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
                'unique_together': {('account_assigned', 'platform')},
            },
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
