# Generated by Django 4.1.2 on 2022-10-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0004_employees_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_assigned',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_team.teams'),
        ),
    ]
