# Generated by Django 4.1.2 on 2022-10-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0005_alter_accounts_account_assigned_alter_employees_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='added_into_tickets_com',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='added_into_tm',
        ),
        migrations.AddField(
            model_name='accounts',
            name='in_tickets_com',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='in_tm',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
