# Generated by Django 4.1.2 on 2022-10-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0006_remove_accounts_added_into_tickets_com_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_assigned',
            field=models.EmailField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='employee', to='accounts_team.employees'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='cvv_number',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='in_tickets_com',
            field=models.BooleanField(verbose_name='Added in TM'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='in_tm',
            field=models.BooleanField(verbose_name='Added in tickets.com'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='team', to='accounts_team.teams'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
