# Generated by Django 4.1.2 on 2022-10-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0007_alter_accounts_account_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_team.employees'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_team.teams'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', related_query_name='employee', to='accounts_team.teams'),
        ),
    ]
