# Generated by Django 4.1.2 on 2022-11-03 01:07

import accounts_team.models
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0008_alter_accounts_created_by_alter_accounts_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='card_number',
            field=models.CharField(max_length=16, validators=[accounts_team.models.clean_card_number]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='cvv_number',
            field=models.CharField(max_length=3, validators=[accounts_team.models.clean_cvv_number]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='expiration_date',
            field=models.CharField(max_length=5, validators=[accounts_team.models.clean_expiration_date]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Employee name'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Team name'),
        ),
        migrations.AddConstraint(
            model_name='accounts',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('account_assigned'), models.OrderBy(django.db.models.functions.text.Lower('platform'), descending=True), name='email_and_platform_unique'),
        ),
    ]
