# Generated by Django 4.1.2 on 2022-11-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0009_accounts_limit_alter_accounts_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_assigned',
            field=models.EmailField(db_index=True, max_length=150),
        ),
    ]
