# Generated by Django 4.1.2 on 2022-11-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0010_alter_accounts_account_assigned'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accounts',
            name='email_and_platform_unique',
        ),
        migrations.AddConstraint(
            model_name='accounts',
            constraint=models.UniqueConstraint(fields=('account_assigned', 'platform'), name='email_and_platform_unique', violation_error_message='The account and the platform already exist!'),
        ),
    ]
