# Generated by Django 4.1.2 on 2022-11-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0011_remove_accounts_email_and_platform_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accounts',
            name='email_and_platform_unique',
        ),
        migrations.AddConstraint(
            model_name='accounts',
            constraint=models.UniqueConstraint(fields=('account_assigned', 'platform'), name='email_and_platform_unique'),
        ),
    ]
