# Generated by Django 4.1.2 on 2022-11-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0012_remove_accounts_email_and_platform_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accounts',
            name='email_and_platform_unique',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='limit',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='accounts',
            unique_together={('account_assigned', 'platform')},
        ),
    ]
