# Generated by Django 4.1.2 on 2022-11-03 09:22

import accounts_team.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_team', '0013_remove_accounts_email_and_platform_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='accounts',
            name='limit',
            field=models.CharField(default='0', max_length=20, validators=[accounts_team.models.clean_limit]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_team.platform'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_team.type'),
        ),
    ]
