repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args: [ --fix, --select, I, --config, django-backend/pyproject.toml ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: ./shell_scripts/run_tests.sh precommit
        language: script
        pass_filenames: false
