version: "3.8"

services:
  django:
    build:
      context: ./django-backend/
      dockerfile: "Dockerfile-dev"
    container_name: django
    env_file:
      - ./django-backend/.env.dev
    volumes:
      - ./django-backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    networks:
      - backend

  pgdb:
    image: postgres
    container_name: pgdb
    env_file:
      - ./django-backend/.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    name: backend
    driver: bridge
