version: "3.8"


services:
  django:
    build:
      context: ./django-backend/
      dockerfile: "Dockerfile-dev"
    container_name: django
    env_file:
      - ./django-backend/.env.dev
    volumes:
      - ./django-backend:/app
    ports:
      - "${DJANGO_PORT_HOST}:${DJANGO_PORT_CONTAINER}"
    depends_on:
      - pgdb
    networks:
      - backend

  pgdb:
    image: postgres
    container_name: pgdb
    env_file:
      - ./django-backend/.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    ports:
      - "${POSTGRES_PORT_HOST}:${POSTGRES_PORT_CONTAINER}"
    restart: unless-stopped
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    name: backend
    driver: bridge
