version: "3.8"


services:
  django:
    build:
      dockerfile: "Dockerfile-dev"
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:
