version: "3.8"


services:
  django:
    build:
      context: ./django-backend/
      dockerfile: "Dockerfile-prod"
    container_name: django
    env_file:
      - ./django-backend/.env.prod
    networks:
      - backend

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    env_file:
      - ./django-backend/.env.prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./django-backend/static/:/static
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - django

networks:
  backend:
    name: backend
    driver: bridge
