# Generated by Django 4.2.4 on 2023-09-14 03:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('season', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'content"."event',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('name_short', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('league', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('ticketmaster_id', models.IntegerField()),
                ('timezone', models.CharField(max_length=255)),
                ('credentials_website', models.CharField(max_length=255)),
                ('ticketmaster_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'content"."team',
            },
        ),
        migrations.CreateModel(
            name='TicketHolder',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                (
                    'phone',
                    models.CharField(blank=True, max_length=255, verbose_name='Phone number'),
                ),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_card_interest', models.BooleanField(default=False)),
                ('is_season_ticket_interest', models.BooleanField(default=False)),
                ('tickets_data', models.JSONField(blank=True, default=dict, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ticket_holder_user',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ticket Holder',
                'verbose_name_plural': 'Ticket Holders',
                'db_table': 'content"."ticket_holder',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('skybox_event_id', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat', models.CharField(max_length=255)),
                ('row', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('barcode', models.IntegerField(blank=True, null=True)),
                ('listing_status', models.CharField(max_length=255)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tickets',
                        to='stt.event',
                    ),
                ),
                (
                    'ticket_holder',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='stt.ticketholder',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'content"."ticket',
            },
        ),
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'event',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stt.event'),
                ),
                (
                    'team',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stt.team'),
                ),
            ],
            options={
                'db_table': 'content"."team_event',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('invoice_number', models.IntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                (
                    'purchase_price',
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ('delivery_status', models.CharField(max_length=255)),
                (
                    'ticket',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stt.ticket'),
                ),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'db_table': 'content"."purchase',
            },
        ),
        migrations.AddConstraint(
            model_name='teamevent',
            constraint=models.UniqueConstraint(fields=('event', 'team'), name='event_team_idx'),
        ),
    ]
