# Generated by Django 4.2.4 on 2023-09-14 04:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHolderTeam',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('credentials_website_username', models.CharField(max_length=255)),
                ('_credentials_website_password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='stt.team'
                    ),
                ),
                (
                    'ticket_holder',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='stt.ticketholder',
                    ),
                ),
            ],
            options={
                'db_table': 'content"."ticket_holder_team',
            },
        ),
        migrations.AddConstraint(
            model_name='ticketholderteam',
            constraint=models.UniqueConstraint(
                fields=('ticket_holder', 'team'), name='ticket_holder_team_idx'
            ),
        ),
    ]
