# Generated by Django 4.2.4 on 2023-09-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketholder',
            name='tickets_data',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
