# Generated by Django 4.2.4 on 2023-09-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0002_alter_ticketholder_tickets_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketholder',
            name='tickets_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
