# Generated by Django 4.2.4 on 2023-09-14 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0002_ticketholderteam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketholderteam',
            old_name='_credentials_website_password',
            new_name='credentials_website_password',
        ),
    ]
