# Generated by Django 4.2.4 on 2023-09-15 13:55

import uuid

import simple_history.models
import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            'stt',
            '0003_rename__credentials_website_password_ticketholderteam_credentials_website_password',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={
                'permissions': (
                    ('import_events', 'Can import'),
                    ('export_events', 'Can export'),
                ),
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                (
                    'id',
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ('name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('season', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(
                        choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                        max_length=1,
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical Event',
                'verbose_name_plural': 'historical Events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
