# Generated by Django 4.2.4 on 2023-09-09 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0003_alter_ticketholder_tickets_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketholder',
            name='is_verified',
        ),
    ]
