# Generated by Django 4.2.4 on 2023-09-18 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0004_alter_event_options_historicalevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={
                'permissions': (
                    ('import_events', 'Can import'),
                    ('export_events', 'Can export'),
                ),
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
