# Generated by Django 4.2.4 on 2023-09-19 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0005_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketholderteam',
            name='ticket_holder',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ticket_holder_teams',
                to='stt.ticketholder',
            ),
        ),
    ]
