# Generated by Django 4.2.4 on 2023-09-20 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0006_alter_ticketholderteam_ticket_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketholderteam',
            name='team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ticket_holder_teams',
                to='stt.team',
            ),
        ),
    ]
