# Generated by Django 4.2.4 on 2023-09-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0007_alter_ticketholderteam_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticketholderteam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
