# Generated by Django 4.2.5 on 2023-09-21 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0010_historicalticketholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalticketholder',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ticketholder',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
