# Generated by Django 4.2.5 on 2023-09-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0011_rename_date_created_historicalticketholder_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(
                fields=('ticket_holder', 'event', 'seat'), name='unique_ticket'
            ),
        ),
    ]
