# Generated by Django 4.2.5 on 2023-10-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0012_ticket_unique_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketholderteam',
            name='row',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketholderteam',
            name='seat',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketholderteam',
            name='section',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
