# Generated by Django 4.2.5 on 2023-10-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0013_ticketholderteam_row_ticketholderteam_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketholderteam',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
