# Generated by Django 4.2.5 on 2023-10-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0014_ticketholderteam_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketholderteam',
            name='is_confirmed',
            field=models.BooleanField(
                default=False, help_text="Is the ticket holder's team data confirmed?"
            ),
        ),
    ]
