# Generated by Django 4.2.5 on 2023-10-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0015_alter_ticketholderteam_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='home_venue',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
