# Generated by Django 4.2.5 on 2023-10-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0016_team_home_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchase',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='skybox_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='skybox_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
