# Generated by Django 4.2.5 on 2023-10-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0017_alter_historicalpurchase_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stt.ticket'),
        ),
    ]
