# Generated by Django 4.2.5 on 2023-10-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0018_alter_purchase_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='season',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='season',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
