# Generated by Django 4.2.5 on 2023-10-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0019_historicalticket_season_ticket_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='created_at',
            field=models.DateTimeField(
                blank=True, default='2023-10-20', editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-20'),
            preserve_default=False,
        ),
    ]
