# Generated by Django 4.2.5 on 2023-10-24 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0020_historicalticket_created_at_ticket_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamevent',
            options={
                'verbose_name': "Event's Team",
                'verbose_name_plural': "Event's Teams",
            },
        ),
        migrations.AlterModelOptions(
            name='ticketholderteam',
            options={
                'verbose_name': "Ticket Holder's Team",
                'verbose_name_plural': "Ticket Holder's Teams",
            },
        ),
    ]
