# Generated by Django 4.2.5 on 2023-10-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0021_alter_teamevent_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamevent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ticketholderteam',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(
                fields=('name', 'date_time', 'season'), name='name_date_time_season_idx'
            ),
        ),
    ]
