# Generated by Django 4.2.5 on 2023-10-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0022_alter_teamevent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2023-10-20', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-20'),
            preserve_default=False,
        ),
    ]
