# Generated by Django 4.2.6 on 2023-11-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0023_historicalpurchase_created_at_purchase_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketholderteam',
            name='tickets_quantity',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
