# Generated by Django 4.2.6 on 2023-11-06 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0024_ticketholderteam_tickets_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketholderteam',
            old_name='tickets_quantity',
            new_name='seats_quantity',
        ),
    ]
