# Generated by Django 4.2.6 on 2023-11-14 06:01

from django.db import migrations, models

import apps.stt.models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0025_rename_tickets_quantity_ticketholderteam_seats_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticketholder',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketholder',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.stt.models.ticket_holder_avatar_path,
            ),
        ),
    ]
