# Generated by Django 4.2.7 on 2023-11-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0026_historicalticketholder_avatar_ticketholder_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
