# Generated by Django 4.2.7 on 2023-11-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0027_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
