# Generated by Django 4.2.7 on 2023-12-06 13:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0028_alter_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('skybox_venue_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'db_table': 'content"."venue',
                'permissions': (
                    ('import_events', 'Can import'),
                    ('export_events', 'Can export'),
                ),
            },
        ),
    ]
