# Generated by Django 4.2.7 on 2023-12-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0029_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_info',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='additional_info',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(
                fields=('skybox_venue_id', 'name'), name='skybox_venue_id_name_idx'
            ),
        ),
    ]
