# Generated by Django 4.2.7 on 2023-12-07 05:55

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0030_event_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='home_venue_new',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='home_teams',
                to='stt.venue',
            ),
        ),
    ]
