# Generated by Django 4.2.7 on 2023-12-07 05:56

from django.db import migrations


def link_venues_to_teams(apps, schema_editor):
    Team = apps.get_model('stt', 'Team')
    Venue = apps.get_model('stt', 'Venue')
    for team in Team.objects.all():
        venue_name = team.home_venue
        venue = Venue.objects.filter(name=venue_name).first()
        if venue:
            team.home_venue_new = venue
            team.save()


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0031_team_home_venue_new'),
    ]

    operations = [
        migrations.RunPython(link_venues_to_teams),
    ]
