# Generated by Django 4.2.7 on 2023-12-07 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0032_auto_20231207_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='home_venue',
        ),
    ]
