# Generated by Django 4.2.7 on 2023-12-07 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0033_remove_team_home_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='home_venue_new',
            new_name='home_venue',
        ),
    ]
