# Generated by Django 4.2.7 on 2023-12-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0034_rename_home_venue_new_team_home_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='skybox_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
