# Generated by Django 4.2.8 on 2023-12-11 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0035_team_skybox_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticketholder',
            name='tickets_data',
        ),
        migrations.RemoveField(
            model_name='ticketholder',
            name='tickets_data',
        ),
    ]
