# Generated by Django 4.2.8 on 2023-12-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0036_remove_historicalticketholder_tickets_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='skybox_event_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='skybox_event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='league',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='skybox_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='stubhub_event_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='league',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='skybox_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='stubhub_event_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
