# Generated by Django 4.2.8 on 2023-12-11 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0037_remove_historicalticket_skybox_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='season',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='season',
        ),
    ]
