# Generated by Django 4.2.8 on 2023-12-11 10:06

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0038_remove_historicalticket_season_remove_ticket_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='events',
                to='stt.venue',
            ),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='venue',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='stt.venue',
            ),
        ),
    ]
