# Generated by Django 4.2.8 on 2023-12-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0039_event_venue_historicalevent_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stubhub_event_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='stubhub_event_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
