# Generated by Django 4.2.8 on 2023-12-15 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0040_alter_event_stubhub_event_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketholderteam',
            options={
                'permissions': (('view_credentials', 'Can view credentials'),),
                'verbose_name': "Ticket Holder's Team",
                'verbose_name_plural': "Ticket Holder's Teams",
            },
        ),
    ]
