# Generated by Django 4.2.8 on 2023-12-15 04:55

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0041_alter_ticketholderteam_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketholderteam',
            name='credentials_website_password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='ticketholderteam',
            name='credentials_website_username',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
