# Generated by Django 4.2.8 on 2023-12-21 08:57

import uuid

import simple_history.models

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stt', '0043_historicalticketholder_timezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSeason',
            fields=[
                (
                    'id',
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='The name or title of the season. For example, "2023", "2023-2024".',
                        max_length=255,
                    ),
                ),
                (
                    'start_year',
                    models.IntegerField(
                        help_text='The calendar year when the season starts'
                    ),
                ),
                (
                    'league',
                    models.CharField(
                        choices=[
                            ('NFL', 'NFL'),
                            ('NBA', 'NBA'),
                            ('NHL', 'NHL'),
                            ('MLB', 'MLB'),
                            ('MLS', 'MLS'),
                        ],
                        help_text='The sports league to which the season belongs',
                        max_length=255,
                    ),
                ),
                (
                    'official_start_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when the season officially starts',
                    ),
                ),
                (
                    'official_end_date',
                    models.DateField(
                        blank=True, help_text='The date when the season officially ends'
                    ),
                ),
                (
                    'start_selling_season_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when sales for season-related tickets begin',
                    ),
                ),
                (
                    'start_regular_season_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when the regular season is scheduled to begin',
                    ),
                ),
                (
                    'end_regular_season_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when the regular season is scheduled to end',
                    ),
                ),
                (
                    'start_playoff_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when the playoff season is scheduled to begin',
                    ),
                ),
                (
                    'end_playoff_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when the playoff season is scheduled to end',
                    ),
                ),
                (
                    'is_selling_season',
                    models.BooleanField(
                        default=False,
                        help_text='A boolean indicating if the season is currently in the selling period',
                    ),
                ),
                (
                    'is_regular_season',
                    models.BooleanField(
                        default=False,
                        help_text='A boolean indicating if the season is currently in the regular season period',
                    ),
                ),
                (
                    'is_playoff_season',
                    models.BooleanField(
                        default=False,
                        help_text='A boolean indicating if the season is currently in the playoff period',
                    ),
                ),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(
                        choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                        max_length=1,
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical Season',
                'verbose_name_plural': 'historical Seasons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='The name or title of the season. For example, "2023", "2023-2024".',
                        max_length=255,
                    ),
                ),
                (
                    'start_year',
                    models.IntegerField(
                        help_text='The calendar year when the season starts'
                    ),
                ),
                (
                    'league',
                    models.CharField(
                        choices=[
                            ('NFL', 'NFL'),
                            ('NBA', 'NBA'),
                            ('NHL', 'NHL'),
                            ('MLB', 'MLB'),
                            ('MLS', 'MLS'),
                        ],
                        help_text='The sports league to which the season belongs',
                        max_length=255,
                    ),
                ),
                (
                    'official_start_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when the season officially starts',
                    ),
                ),
                (
                    'official_end_date',
                    models.DateField(
                        blank=True, help_text='The date when the season officially ends'
                    ),
                ),
                (
                    'start_selling_season_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when sales for season-related tickets begin',
                    ),
                ),
                (
                    'start_regular_season_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when the regular season is scheduled to begin',
                    ),
                ),
                (
                    'end_regular_season_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when the regular season is scheduled to end',
                    ),
                ),
                (
                    'start_playoff_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when the playoff season is scheduled to begin',
                    ),
                ),
                (
                    'end_playoff_date',
                    models.DateField(
                        blank=True,
                        help_text='The date when the playoff season is scheduled to end',
                    ),
                ),
                (
                    'is_selling_season',
                    models.BooleanField(
                        default=False,
                        help_text='A boolean indicating if the season is currently in the selling period',
                    ),
                ),
                (
                    'is_regular_season',
                    models.BooleanField(
                        default=False,
                        help_text='A boolean indicating if the season is currently in the regular season period',
                    ),
                ),
                (
                    'is_playoff_season',
                    models.BooleanField(
                        default=False,
                        help_text='A boolean indicating if the season is currently in the playoff period',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'db_table': 'content"."season',
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(
                fields=('name', 'league', 'start_year'), name='unique_season_details'
            ),
        ),
        migrations.AddField(
            model_name='historicalseason',
            name='history_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
