# Generated by Django 4.2.8 on 2023-12-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0045_alter_historicalseason_end_playoff_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='season',
            new_name='old_season',
        ),
        migrations.RenameField(
            model_name='historicalevent',
            old_name='season',
            new_name='old_season',
        ),
    ]
