# Generated by Django 4.2.8 on 2023-12-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0046_rename_season_event_old_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='stt.season'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='season',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stt.season'),
        ),
    ]
