# Generated by Django 4.2.8 on 2023-12-22 07:35

from django.db import migrations


def map_old_season_to_new(apps, schema_editor):
    Event = apps.get_model('stt', 'Event')
    Season = apps.get_model('stt', 'Season')
    for event in Event.objects.all():
        event.season, created = Season.objects.get_or_create(
            name=event.old_season,
            start_year=int(event.old_season),
            league=event.league,
        )
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0047_event_season_historicalevent_season'),
    ]

    operations = [
        migrations.RunPython(map_old_season_to_new),
    ]
