# Generated by Django 4.2.8 on 2023-12-22 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0048_auto_20231222_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='old_season',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='old_season',
        ),
    ]
