# Generated by Django 4.2.8 on 2024-01-01 03:54

import uuid

import django_cryptography.fields
import simple_history.models

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stt', '0050_alter_historicalticketholder_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketholderteam',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticketholderteam',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='HistoricalTicketHolderTeam',
            fields=[
                (
                    'id',
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ('section', models.CharField(max_length=255)),
                ('row', models.CharField(max_length=255)),
                ('seat', models.CharField(max_length=255)),
                (
                    'seats_quantity',
                    models.PositiveIntegerField(default=1, editable=False),
                ),
                (
                    'credentials_website_username',
                    django_cryptography.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    'credentials_website_password',
                    django_cryptography.fields.encrypt(models.CharField(max_length=255)),
                ),
                (
                    'is_confirmed',
                    models.BooleanField(
                        default=False,
                        help_text="Is the ticket holder's team data confirmed?",
                    ),
                ),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(
                        choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                        max_length=1,
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='stt.team',
                    ),
                ),
                (
                    'ticket_holder',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='stt.ticketholder',
                    ),
                ),
            ],
            options={
                'verbose_name': "historical Ticket Holder's Team",
                'verbose_name_plural': "historical Ticket Holder's Teams",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
