# Generated by Django 4.2.8 on 2024-01-01 06:48

import datetime
import uuid

import simple_history.models

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stt', '0051_remove_ticketholderteam_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamevent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 1, 6, 48, 33, 495761, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='created_at',
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 1, 1, 6, 48, 43, 318167, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalseason',
            name='created_at',
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 1, 1, 6, 48, 45, 344950, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalticketholderteam',
            name='created_at',
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 1, 1, 6, 48, 47, 768976, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 1, 6, 48, 49, 277212, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 1, 6, 48, 50, 722248, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketholderteam',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 1, 6, 48, 52, 576018, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 1, 1, 6, 48, 55, 358771, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoricalTeamEvent',
            fields=[
                (
                    'id',
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(
                        choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                        max_length=1,
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='stt.event',
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='stt.team',
                    ),
                ),
            ],
            options={
                'verbose_name': "historical Event's Team",
                'verbose_name_plural': "historical Event's Teams",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
