# Generated by Django 4.2.10 on 2024-02-22 02:11

from django.db import migrations, models

import apps.stt.models.ticket_holder


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0052_remove_teamevent_updated_at_event_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ticketmaster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketholder',
            name='avatar',
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.stt.models.ticket_holder.ticket_holder_avatar_path
            ),
        ),
    ]
