# Generated by Django 4.2.10 on 2024-03-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0053_alter_team_ticketmaster_id_alter_ticketholder_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalseason',
            name='league',
            field=models.CharField(
                choices=[
                    ('NFL', 'NFL'),
                    ('NBA', 'NBA'),
                    ('NHL', 'NHL'),
                    ('MLB', 'MLB'),
                    ('MLS', 'MLS'),
                    ('NCAAF', 'NCAAF'),
                ],
                help_text='The sports league to which the season belongs',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='season',
            name='league',
            field=models.CharField(
                choices=[
                    ('NFL', 'NFL'),
                    ('NBA', 'NBA'),
                    ('NHL', 'NHL'),
                    ('MLB', 'MLB'),
                    ('MLS', 'MLS'),
                    ('NCAAF', 'NCAAF'),
                ],
                help_text='The sports league to which the season belongs',
                max_length=255,
            ),
        ),
    ]
