# Generated by Django 4.2.11 on 2024-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0054_alter_historicalseason_league_alter_season_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='vendor_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
