# Generated by Django 4.2.11 on 2024-03-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0055_team_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='automatiq_credentials_website_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
