# Generated by Django 4.2.11 on 2024-03-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0056_team_automatiq_credentials_website_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
