# Generated by Django 4.2.11 on 2024-03-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stt', '0057_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='credentials_website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='home_venue',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='home_teams',
                to='stt.venue',
            ),
        ),
    ]
