# Generated by Django 3.2.17 on 2023-02-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='facebook_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='twitter_created',
            field=models.BooleanField(default=False),
        ),
    ]
