# Generated by Django 3.2.17 on 2023-02-13 09:56

import simple_history.models

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common_services.validators


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20230210_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAccounts',
            fields=[
                (
                    'id',
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name='ID'
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        max_length=100,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        max_length=100,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                ('email', models.EmailField(db_index=True, max_length=150)),
                (
                    'type',
                    models.CharField(
                        max_length=100,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                (
                    'password',
                    models.CharField(
                        max_length=32,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                ('recovery_email', models.EmailField(max_length=150)),
                ('email_forwarding', models.BooleanField(default=False)),
                ('auto_po_seats_scouts', models.BooleanField(default=False)),
                (
                    'errors_failed',
                    models.CharField(
                        max_length=255,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                ('tm_created', models.BooleanField(default=False)),
                (
                    'tm_password',
                    models.CharField(
                        max_length=32,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                (
                    'tm_address',
                    models.CharField(
                        default='NA',
                        max_length=255,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                ('axs_created', models.BooleanField(default=False)),
                (
                    'axs_password',
                    models.CharField(
                        max_length=32,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                ('sg_created', models.BooleanField(default=False)),
                (
                    'sg_password',
                    models.CharField(
                        max_length=32,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                ('tickets_com_created', models.BooleanField(default=False)),
                ('facebook_created', models.BooleanField(default=False)),
                ('twitter_created', models.BooleanField(default=False)),
                ('eventbrite', models.BooleanField(default=False)),
                ('etix', models.BooleanField(default=False)),
                ('ticket_web', models.BooleanField(default=False)),
                ('big_tickets', models.BooleanField(default=False)),
                ('amazon', models.BooleanField(default=False)),
                (
                    'secondary_password',
                    models.CharField(
                        max_length=32,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                ('seat_scouts_added', models.BooleanField(default=False)),
                ('seat_scouts_status', models.BooleanField(default=False)),
                (
                    'team',
                    models.CharField(
                        max_length=255,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                (
                    'specific_team',
                    models.CharField(
                        max_length=255,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                (
                    'forward_to',
                    models.CharField(
                        max_length=150,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                (
                    'forward_email_password',
                    models.CharField(
                        max_length=32,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                (
                    'seat_scouts_password',
                    models.CharField(
                        max_length=32,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                ('password_matching', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                (
                    'created_by',
                    models.CharField(
                        default='MATEEN',
                        max_length=32,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                (
                    'edited_by',
                    models.CharField(
                        default='NA',
                        max_length=32,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                (
                    'ld_computer_used',
                    models.CharField(
                        max_length=50,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                ('created_at', models.DateField(blank=True, null=True)),
                (
                    'updated_at',
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ('last_opened', models.DateField(blank=True, null=True)),
                (
                    'comments',
                    models.TextField(
                        validators=[apps.common_services.validators.any_or_na]
                    ),
                ),
                (
                    'phone',
                    models.CharField(
                        default='NA',
                        max_length=50,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                (
                    'tickets_com_password',
                    models.CharField(
                        default='NA',
                        max_length=50,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                ('password_reset', models.BooleanField(default=False)),
                ('active_tickets_inside', models.BooleanField(default=False)),
                (
                    'migrated_from',
                    models.CharField(
                        default='NA',
                        max_length=100,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                (
                    'migrated_to',
                    models.CharField(
                        default='NA',
                        max_length=100,
                        validators=[apps.common_services.validators.any_or_na],
                    ),
                ),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(
                        choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                        max_length=1,
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical Account',
                'verbose_name_plural': 'historical Accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
