# Generated by Django 3.2.17 on 2023-02-17 03:34

from django.db import migrations, models

import apps.validators


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_historicalaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='delta_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='delta_password',
            field=models.CharField(
                default='NA', max_length=32, validators=[apps.validators.any_or_na]
            ),
        ),
    ]
