# Generated by Django 3.2.17 on 2023-03-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230216_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalaccounts',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
