# Generated by Django 3.2.18 on 2023-04-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_auto_20230309_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='delta_miles',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='flyingblue_miles',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='delta_miles',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='flyingblue_miles',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
