# Generated by Django 4.2.1 on 2023-06-08 01:18

from django.db import migrations, models

import apps.common_services.validators


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_auto_20230409_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='am_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='am_password',
            field=models.CharField(
                default='',
                max_length=255,
                validators=[apps.common_services.validators.any_or_na],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='paciolan_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='paciolan_password',
            field=models.CharField(
                default='',
                max_length=255,
                validators=[apps.common_services.validators.any_or_na],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='am_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='am_password',
            field=models.CharField(
                default='',
                max_length=255,
                validators=[apps.common_services.validators.any_or_na],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='paciolan_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='paciolan_password',
            field=models.CharField(
                default='',
                max_length=255,
                validators=[apps.common_services.validators.any_or_na],
            ),
            preserve_default=False,
        ),
    ]
