# Generated by Django 4.1.3 on 2022-11-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('email_provider', models.EmailField(blank=True, db_index=True, max_length=150, null=True)),
                ('forward_email', models.EmailField(blank=True, db_index=True, max_length=150, null=True)),
                ('forward_email_password', models.CharField(blank=True, max_length=32, null=True)),
                ('email_forwarding', models.BooleanField(default=False)),
                ('auto_po_seats_scouts', models.BooleanField(default=False)),
                ('errors_failed', models.CharField(blank=True, max_length=255, null=True)),
                ('seat_scouts_added', models.BooleanField(default=False)),
                ('seat_scouts_status', models.BooleanField(default=False)),
                ('seat_scouts_password', models.CharField(blank=True, max_length=32, null=True)),
                ('password_matching', models.BooleanField(default=False)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('tm_address', models.CharField(blank=True, max_length=255, null=True)),
                ('tm_password', models.CharField(blank=True, max_length=32, null=True)),
                ('axs_password', models.CharField(blank=True, max_length=32, null=True)),
                ('sg_password', models.CharField(blank=True, max_length=32, null=True)),
                ('in_tickets_com', models.BooleanField(default=False)),
                ('eventbrite', models.BooleanField(default=False)),
                ('etix', models.BooleanField(default=False)),
                ('ticket_web', models.BooleanField(default=False)),
                ('big_tickets', models.BooleanField(default=False)),
                ('amazon', models.BooleanField(default=False)),
                ('secondary_password', models.CharField(blank=True, max_length=32, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('ld_computer_used', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
