# Generated by Django 4.1.3 on 2022-12-15 03:15

import cards.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[cards.validators.any_or_na])),
                ('last_name', models.CharField(max_length=100, validators=[cards.validators.any_or_na])),
                ('email', models.EmailField(db_index=True, max_length=150)),
                ('type', models.CharField(max_length=100, validators=[cards.validators.any_or_na])),
                ('password', models.CharField(max_length=32, validators=[cards.validators.any_or_na])),
                ('recovery_email', models.EmailField(max_length=150)),
                ('email_forwarding', models.BooleanField(default=False)),
                ('auto_po_seats_scouts', models.BooleanField(default=False)),
                ('errors_failed', models.CharField(max_length=255, validators=[cards.validators.any_or_na])),
                ('tm_created', models.BooleanField(default=False)),
                ('tm_password', models.CharField(max_length=32, validators=[cards.validators.any_or_na])),
                ('axs_created', models.BooleanField(default=False)),
                ('axs_password', models.CharField(max_length=32, validators=[cards.validators.any_or_na])),
                ('sg_created', models.BooleanField(default=False)),
                ('sg_password', models.CharField(max_length=32, validators=[cards.validators.any_or_na])),
                ('tickets_com_created', models.BooleanField(default=False)),
                ('eventbrite', models.BooleanField(default=False)),
                ('etix', models.BooleanField(default=False)),
                ('ticket_web', models.BooleanField(default=False)),
                ('big_tickets', models.BooleanField(default=False)),
                ('amazon', models.BooleanField(default=False)),
                ('secondary_password', models.CharField(max_length=32, validators=[cards.validators.any_or_na])),
                ('seat_scouts_added', models.BooleanField(default=False)),
                ('seat_scouts_status', models.BooleanField(default=False)),
                ('airfrance', models.BooleanField(default=False)),
                ('team', models.CharField(max_length=255, validators=[cards.validators.any_or_na])),
                ('specific_team', models.CharField(max_length=255, validators=[cards.validators.any_or_na])),
                ('forward_to', models.CharField(max_length=150, validators=[cards.validators.any_or_na])),
                ('forward_email_password', models.CharField(max_length=32, validators=[cards.validators.any_or_na])),
                ('disabled', models.BooleanField(default=False)),
                ('ld_computer_used', models.CharField(max_length=50, validators=[cards.validators.any_or_na])),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_opened', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_accounts_set', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_by_accounts_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
                'permissions': (('import_accounts', 'Can import'), ('export_accounts', 'Can export')),
            },
        ),
    ]
