# Generated by Django 4.1.3 on 2022-11-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='in_tickets_com',
            new_name='airfrance',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='is_disabled',
            new_name='axs_created',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='email_provider',
            new_name='forward_to',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='forward_email',
            new_name='recovery_email',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='tm_address',
            new_name='recovery_or_disabled',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='accounts',
            name='edited_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='last_opened',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='sg_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='specific_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='ticket_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='tickets_com_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='tm_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='tm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
