# Generated by Django 4.1.3 on 2022-11-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='in_tickets_com',
            field=models.BooleanField(default=False, verbose_name='tickets.com'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='in_tm',
            field=models.BooleanField(default=False, verbose_name='TM'),
        ),
    ]
