# Generated by Django 4.1.4 on 2022-12-28 06:52

import cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='comments',
            field=models.TextField(default='NA', validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
    ]
