# Generated by Django 4.1.3 on 2022-11-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_in_tickets_com_alter_accounts_in_tm'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
