# Generated by Django 4.1.3 on 2022-11-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_in_tickets_com_accounts_airfrance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_opened',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
