# Generated by Django 4.1.3 on 2022-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_created_at_alter_accounts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
