# Generated by Django 4.1.3 on 2022-11-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_created_at_alter_accounts_last_opened'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='password_matching',
            new_name='disabled',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='recovery_or_disabled',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='seat_scouts_password',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='accounts',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='ld_computer_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='tm_password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
