# Generated by Django 4.1.3 on 2022-11-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_password_matching_accounts_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
