# Generated by Django 4.1.3 on 2022-11-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accounts_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_opened',
            field=models.DateField(blank=True, null=True),
        ),
    ]
