# Generated by Django 4.1.3 on 2022-11-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_accounts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
