# Generated by Django 4.1.3 on 2022-12-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_accounts_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['-created_at'], 'permissions': (('import_accounts', 'Can import'), ('export_accounts', 'Can export')), 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
