# Generated by Django 4.1.3 on 2022-12-05 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_alter_accounts_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_accounts_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_by_accounts_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
