# Generated by Django 4.1.3 on 2022-12-07 05:56

import cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_accounts_created_by_alter_accounts_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='axs_password',
            field=models.CharField(default='NA', max_length=32, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='errors_failed',
            field=models.CharField(default='NA', max_length=255, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(default='NA', max_length=100, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='forward_email_password',
            field=models.CharField(default='NA', max_length=32, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='forward_to',
            field=models.CharField(default='NA', max_length=150, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(default='NA', max_length=100, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='ld_computer_used',
            field=models.CharField(default='NA', max_length=50, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(default='NA', max_length=32, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='recovery_email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='secondary_password',
            field=models.CharField(default='NA', max_length=32, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='sg_password',
            field=models.CharField(default='NA', max_length=32, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='specific_team',
            field=models.CharField(default='NA', max_length=255, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='team',
            field=models.CharField(default='NA', max_length=255, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='tm_password',
            field=models.CharField(default='NA', max_length=32, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='type',
            field=models.CharField(default='NA', max_length=100, validators=[cards.validators.any_or_na]),
            preserve_default=False,
        ),
    ]
