# Generated by Django 3.2.17 on 2023-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_numbers', '0002_historicalmobilenumbertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmobilenumbertransaction',
            name='awake_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmobilenumbertransaction',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmobilenumbertransaction',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='historicalmobilenumbertransaction',
            name='status',
            field=models.TextField(
                choices=[
                    ('expiring soon', 'Expiring Soon'),
                    ('expired', 'Expired'),
                    ('offline', 'Offline'),
                    ('online', 'Online'),
                    ('not applicable', 'Not Applicable'),
                ],
                default='not applicable',
            ),
        ),
        migrations.AddField(
            model_name='mobilenumbertransaction',
            name='awake_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilenumbertransaction',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilenumbertransaction',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='mobilenumbertransaction',
            name='status',
            field=models.TextField(
                choices=[
                    ('expiring soon', 'Expiring Soon'),
                    ('expired', 'Expired'),
                    ('offline', 'Offline'),
                    ('online', 'Online'),
                    ('not applicable', 'Not Applicable'),
                ],
                default='not applicable',
            ),
        ),
    ]
