# Generated by Django 3.2.17 on 2023-03-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mobile_numbers', '0003_auto_20230227_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmobilenumbertransaction',
            name='type',
            field=models.TextField(
                choices=[
                    ('temporary', 'Temporary'),
                    ('rental', 'Rental'),
                    ('not applicable', 'Not Applicable'),
                ],
                default='not applicable',
            ),
        ),
        migrations.AddField(
            model_name='mobilenumbertransaction',
            name='type',
            field=models.TextField(
                choices=[
                    ('temporary', 'Temporary'),
                    ('rental', 'Rental'),
                    ('not applicable', 'Not Applicable'),
                ],
                default='not applicable',
            ),
        ),
    ]
