# Generated by Django 4.2 on 2023-04-27 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mobile_numbers', '0004_auto_20230301_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilenumbertransaction',
            options={
                'ordering': ['-created_at'],
                'permissions': (
                    ('import_mobile_numbers', 'Can import'),
                    ('export_mobile_numbers', 'Can export'),
                ),
                'verbose_name': 'Mobile Number Transaction',
                'verbose_name_plural': 'Mobile Number Transactions',
            },
        ),
    ]
