# Generated by Django 4.1.3 on 2022-11-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLBSoldInventory',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('in_hand_date', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('row', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.CharField(blank=True, max_length=50, null=True)),
                ('face_value', models.CharField(blank=True, max_length=50, null=True)),
                ('list_price', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_cost_average', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('fulfillment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('profit', models.CharField(blank=True, max_length=100, null=True)),
                ('profit_margin', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('fulfillment_date', models.DateTimeField(blank=True, null=True)),
                ('invoiceTags', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_ticket_sales', models.CharField(blank=True, max_length=100, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_venue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('performer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('performer_category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('performer_category_type', models.CharField(blank=True, max_length=100, null=True)),
                ('row_count', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_ids', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
