# Generated by Django 4.1.3 on 2022-11-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sold_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlbsoldinventory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'MLB Sold Inventory', 'verbose_name_plural': 'MLB Sold Inventories'},
        ),
        migrations.RenameField(
            model_name='mlbsoldinventory',
            old_name='invoiceTags',
            new_name='invoice_tags',
        ),
    ]
