# Generated by Django 4.1.3 on 2022-11-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sold_inventory', '0002_alter_mlbsoldinventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbsoldinventory',
            name='edited_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mlbsoldinventory',
            name='extra_tickets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mlbsoldinventory',
            name='filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mlbsoldinventory',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mlbsoldinventory',
            name='order_email',
            field=models.EmailField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mlbsoldinventory',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mlbsoldinventory',
            name='po',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mlbsoldinventory',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mlbsoldinventory',
            name='upgraded_section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
