# Generated by Django 4.1.3 on 2022-11-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sold_inventory', '0003_mlbsoldinventory_edited_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlbsoldinventory',
            options={'ordering': ['-id'], 'verbose_name': 'MLB Sold Inventory', 'verbose_name_plural': 'MLB Sold Inventories'},
        ),
    ]
