# Generated by Django 3.2.17 on 2023-02-13 09:56

import simple_history.models

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.validators


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCards',
            fields=[
                (
                    'id',
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name='ID'
                    ),
                ),
                ('account_assigned', models.EmailField(db_index=True, max_length=150)),
                ('platform', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                (
                    'parent_card',
                    models.CharField(
                        max_length=150, validators=[apps.validators.any_or_na]
                    ),
                ),
                (
                    'card_number',
                    models.CharField(
                        max_length=16,
                        validators=[apps.cards.validators.clean_card_number],
                    ),
                ),
                (
                    'expiration_date',
                    models.CharField(
                        max_length=5,
                        validators=[apps.cards.validators.clean_expiration_date],
                    ),
                ),
                (
                    'cvv_number',
                    models.CharField(
                        max_length=4,
                        validators=[apps.cards.validators.clean_cvv_number],
                    ),
                ),
                ('created_at', models.DateField(blank=True, editable=False)),
                ('updated_at', models.DateField(blank=True, editable=False)),
                ('team', models.CharField(max_length=20)),
                (
                    'specific_team',
                    models.CharField(
                        max_length=100, validators=[apps.validators.any_or_na]
                    ),
                ),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                (
                    'state',
                    models.CharField(
                        max_length=2, validators=[apps.cards.validators.clean_state]
                    ),
                ),
                (
                    'zip_code',
                    models.CharField(
                        max_length=5, validators=[apps.cards.validators.clean_zip_code]
                    ),
                ),
                ('in_tm', models.BooleanField(default=False)),
                ('in_tickets_com', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(
                        choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                        max_length=1,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical Card',
                'verbose_name_plural': 'historical Cards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
