from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework.permissions import IsAuthenticated

from django.urls import path

schema_view = get_schema_view(
    openapi.Info(
        title='Lew & Dowski STT Backend API',
        default_version='v1',
        description='This is autogenerated swagger UI',
        contact=openapi.Contact(email='asamoilov@lewanddowski.com'),
        license=openapi.License(name='BSD License'),
    ),
    public=True,
    permission_classes=[IsAuthenticated],
)

urlpatterns = [
    path(
        'api/v1/swagger<format>/',
        schema_view.without_ui(cache_timeout=0),
        name='schema-json',
    ),
    path(
        'api/v1/swagger/',
        schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui',
    ),
    path(
        'api/v1/redoc/',
        schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc',
    ),
]
