# Generated by Django 4.1.8 on 2023-04-18 03:30

import uuid

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='USAddresses',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('city', models.CharField(blank=True, max_length=255)),
                ('line', models.CharField(blank=True, max_length=255)),
                ('street_name', models.CharField(blank=True, max_length=255)),
                ('street_number', models.CharField(blank=True, max_length=255)),
                ('street_suffix', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('state_code', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    'location',
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'US Address',
                'verbose_name_plural': 'US Addresses',
                'db_table': 'content"."us_addresses',
                'ordering': ['state'],
                'permissions': (
                    ('import_accounts', 'Can import'),
                    ('export_accounts', 'Can export'),
                ),
            },
        ),
    ]
