# Generated by Django 4.1.8 on 2023-04-19 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('us_addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usaddresses',
            unique_together={('line', 'city')},
        ),
    ]
