# Generated by Django 4.2 on 2023-04-27 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('us_addresses', '0002_alter_usaddresses_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usaddresses',
            options={
                'ordering': ['state'],
                'permissions': (
                    ('import_us_addresses', 'Can import'),
                    ('export_us_addresses', 'Can export'),
                ),
                'verbose_name': 'US Address',
                'verbose_name_plural': 'US Addresses',
            },
        ),
    ]
