import os
from datetime import timedelta

from config.components.redis import REDIS_URL

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', REDIS_URL)
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_AGGREGATED_SLACK_NOTIFICATION_COUNTDOWN = int(
    os.environ.get('CELERY_AGGREGATED_SLACK_NOTIFICATION_COUNTDOWN', 30)
)
CELERY_GENERAL_COUNTDOWN = int(os.environ.get('CELERY_GENERAL_COUNTDOWN', 5))
CELERY_RESULT_EXTENDED = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERY_TASK_RESULT_EXPIRES = None
CELERY_TASK_RESULT_MAX_AGE = timedelta(days=7)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = os.environ.get(
    'CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP', True
)
