import os

from config.components.redis import REDIS_URL

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', REDIS_URL)
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_AGGREGATED_SLACK_NOTIFICATION_COUNTDOWN = os.environ.get(
    'CELERY_AGGREGATED_SLACK_NOTIFICATION_COUNTDOWN', 30
)
CELERY_GENERAL_COOLDOWN = os.environ.get('CELERY_GENERAL_COOLDOWN', 5)
