import os

STT_NOTIFICATIONS_CHANNEL_WEBHOOK_URL = os.environ.get(
    'STT_NOTIFICATIONS_CHANNEL_WEBHOOK_URL'
)
STT_NOTIFICATIONS_CHANNEL_TICKET_URL = os.environ.get(
    'STT_NOTIFICATIONS_CHANNEL_TICKET_URL'
)
STT_NOTIFICATIONS_BOT_API_TOKEN = os.environ.get('STT_NOTIFICATIONS_BOT_API_TOKEN')
