# Generated by Django 3.2.17 on 2023-03-06 07:20

import uuid

import simple_history.models

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmailDomains',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                (
                    'id',
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    'domain_name',
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    'status',
                    models.TextField(
                        choices=[
                            ('active', 'Active'),
                            ('pending', 'Pending'),
                            ('not active', 'Not Active'),
                            ('not applicable', 'Not Applicable'),
                        ],
                        default='not applicable',
                    ),
                ),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_default_route', models.BooleanField(default=False)),
                ('is_second_domain', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(
                        choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                        max_length=1,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical Email Domain',
                'verbose_name_plural': 'historical Email Domains',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmailDomains',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'domain_name',
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    'status',
                    models.TextField(
                        choices=[
                            ('active', 'Active'),
                            ('pending', 'Pending'),
                            ('not active', 'Not Active'),
                            ('not applicable', 'Not Applicable'),
                        ],
                        default='not applicable',
                    ),
                ),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_default_route', models.BooleanField(default=False)),
                ('is_second_domain', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=30)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Email Domain',
                'verbose_name_plural': 'Email Domains',
                'db_table': 'content"."email_domains',
                'ordering': ['-created_at'],
                'permissions': (
                    ('import_accounts', 'Can import'),
                    ('export_accounts', 'Can export'),
                ),
            },
        ),
    ]
