# Generated by Django 3.2.17 on 2023-03-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('email_domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildomains',
            name='forwarding_account',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='historicalemaildomains',
            name='forwarding_account',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
