# Generated by Django 4.2 on 2023-04-27 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('email_domains', '0002_auto_20230309_0451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaildomains',
            options={
                'ordering': ['-created_at'],
                'permissions': (
                    ('import_email_domains', 'Can import'),
                    ('export_email_domains', 'Can export'),
                ),
                'verbose_name': 'Email Domain',
                'verbose_name_plural': 'Email Domains',
            },
        ),
    ]
