# Generated by Django 4.2.4 on 2023-09-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether the user has verified his email.',
            ),
        ),
    ]
