# pull official base image (platform must be linux/amd64 due to different CPU architecture between
# local Mac M1 and server linux.
# Alpine is not working for some reason
FROM --platform=linux/amd64 python:3.11

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    NEW_RELIC_CONFIG_FILE=newrelic.ini \
    NEW_RELIC_ENVIRONMENT=production \
    NEW_RELIC_LOG=stdout \
    NEW_RELIC_LOG_LEVEL=info \
    POETRY_VERSION=1.4.2 \
    GUNICORN_TIMEOUT=30

RUN pip install "poetry==$POETRY_VERSION"

COPY poetry.lock pyproject.toml ./

RUN poetry config virtualenvs.create false && \
    poetry install --no-dev

RUN groupadd -r django_group && \
    useradd -r -g django_group django_user

COPY . .

RUN chown -R django_user:django_group /app
RUN mkdir -p /app/media/django-import-export && \
    chown -R django_user:django_group /app/media && \
    chmod -R 775 /app/media && \
    chown -R django_user:django_group /app/media/django-import-export && \
    chmod -R 775 /app/media/django-import-export

RUN python manage.py collectstatic --noinput

USER django_user

CMD python manage.py migrate --noinput && \
    gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout $GUNICORN_TIMEOUT
