FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    POETRY_VERSION=1.4.2

WORKDIR /app

RUN apt-get update && \
    apt-get install -y binutils libproj-dev gdal-bin

RUN pip install "poetry==$POETRY_VERSION"

COPY poetry.lock pyproject.toml ./

RUN poetry config virtualenvs.create false && \
    poetry install

COPY . .

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
