# pull official base image (platform must be linux/amd64 due to different CPU architecture between
# local Mac M1 and server linux.
# Alpine is not working for some reason
FROM --platform=linux/amd64 python:3.11

# set work directory
WORKDIR /app

# set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    NEW_RELIC_CONFIG_FILE=newrelic.ini \
    NEW_RELIC_ENVIRONMENT=production \
    NEW_RELIC_LOG=stdout \
    NEW_RELIC_LOG_LEVEL=info

# install dependencies
COPY ./prod-requirements.txt .
RUN pip install --no-cache-dir -r prod-requirements.txt

# create django_group and django_user
RUN groupadd -r django_group && \
    useradd -r -g django_group django_user

# copy project
COPY . .

# change ownership to django_user and django_group
RUN chown -R django_user:django_group /app

# collect static files
RUN python manage.py collectstatic --noinput

# set user to django_user
USER django_user

# run gunicorn
CMD python manage.py migrate --noinput && \
    gunicorn config.wsgi:application --bind 0.0.0.0:8000
