[build-system]
requires = ["poetry-core>=1.4.2"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "django-backend"
version = "0.1.0"
description = "Django backend for lewanddowski-crm based on django rest framework."
authors = ["Artem Samoilov <asamoilov@lewanddowski.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
dj-database-url = "^1.2.0"
django = "^4.1"
django-cachalot = "^2.5.2"
django-cors-headers = "^3.13.0"
django-debug-toolbar = "^3.8.1"
django-filter = "^22.1"
django-import-export = "^3.0.2"
django-redis = "^5.2.0"
django-simple-history = "^3.2.0"
django-split-settings = "^1.2.0"
django-templated-mail = "^1.1.1"
django-truncate = "^0.1"
djangorestframework = "^3.13.1"
djangorestframework-api-key = "^2.2.0"
djangorestframework-simplejwt = "^4.8.0"
djoser = "^2.1.0"
drf-flex-fields = "^1.0.0"
drf-yasg = "^1.21.4"
faker = "^17.6.0"
gunicorn = "^20.1.0"
newrelic = "^8.7.0"
psycopg2 = "^2.9.6"
psycopg2-binary = "^2.9.6"
python-dotenv = "^0.21.0"
pygount = "^1.5.1"
rollbar = "^0.16.3"
whitenoise = "^6.3.0"

[tool.poetry.group.dev.dependencies]
coverage = "^7.2"
pre-commit = "^3.2"
pandas = "^2.0"


[tool.isort]
known_first_party = "apps, config, tests"
known_django = "django"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "LOCALFOLDER"]
