# Generated by Django 4.1.4 on 2023-01-30 09:47

import uuid

import django.db.models.deletion
import phone_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNumberStorage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'phone',
                    phone_field.models.PhoneField(
                        blank=True, max_length=31, unique=True
                    ),
                ),
                (
                    'status',
                    models.TextField(
                        choices=[
                            ('assigned', 'Assigned'),
                            ('not assigned', 'Not Assigned'),
                        ]
                    ),
                ),
                ('last_time_used', models.DateTimeField(blank=True)),
                ('session_data', models.JSONField(blank=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'email',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='accounts.accounts',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Mobile Number Storage',
                'verbose_name_plural': 'Mobile Numbers Storage',
                'ordering': ['-created_at'],
                'permissions': (
                    ('import_accounts', 'Can import'),
                    ('export_accounts', 'Can export'),
                ),
            },
        ),
    ]
