# Generated by Django 3.2.17 on 2023-02-03 05:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNumberTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service_name', models.CharField(blank=True, max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('service_id', models.CharField(blank=True, max_length=100)),
                ('service_main_response', models.JSONField(blank=True)),
                ('account_created', models.BooleanField(default=False)),
                (
                    'email',
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='accounts.accounts',
                    ),
                ),
                (
                    'requested_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Mobile Number Transaction',
                'verbose_name_plural': 'Mobile Number Transactions',
                'ordering': ['-created_at'],
                'permissions': (
                    ('import_accounts', 'Can import'),
                    ('export_accounts', 'Can export'),
                ),
                'unique_together': {('phone', 'order_id')},
            },
        ),
    ]
