# Generated by Django 4.1.3 on 2022-11-14 03:03

import cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_assigned', models.EmailField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Account')),
                ('platform', models.CharField(blank=True, max_length=255, null=True, verbose_name='Platform')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('parent_card', models.CharField(blank=True, max_length=150, null=True, verbose_name='Parent')),
                ('card_number', models.CharField(blank=True, max_length=16, validators=[cards.validators.clean_card_number])),
                ('expiration_date', models.CharField(blank=True, max_length=5, null=True, validators=[cards.validators.clean_expiration_date], verbose_name='Exp.date')),
                ('cvv_number', models.CharField(blank=True, max_length=4, null=True, validators=[cards.validators.clean_cvv_number], verbose_name='CVV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True, validators=[cards.validators.clean_state])),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, validators=[cards.validators.clean_zip_code])),
                ('in_tm', models.BooleanField(default=False, verbose_name='in TM')),
                ('in_tickets_com', models.BooleanField(default=False, verbose_name='in tickets.com')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
                'unique_together': {('account_assigned', 'platform')},
            },
        ),
    ]
