# Generated by Django 4.1.3 on 2022-12-15 03:15

import cards.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_assigned', models.EmailField(db_index=True, max_length=150)),
                ('platform', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('parent_card', models.CharField(max_length=150, validators=[cards.validators.any_or_na])),
                ('card_number', models.CharField(max_length=16, validators=[cards.validators.clean_card_number])),
                ('expiration_date', models.CharField(max_length=5, validators=[cards.validators.clean_expiration_date])),
                ('cvv_number', models.CharField(max_length=4, validators=[cards.validators.clean_cvv_number])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('team', models.CharField(max_length=20)),
                ('specific_team', models.CharField(max_length=100, validators=[cards.validators.any_or_na])),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2, validators=[cards.validators.clean_state])),
                ('zip_code', models.CharField(max_length=5, validators=[cards.validators.clean_zip_code])),
                ('in_tm', models.BooleanField(default=False)),
                ('in_tickets_com', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_cards_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
                'permissions': (('import_cards', 'Can import'), ('export_cards', 'Can export')),
                'unique_together': {('account_assigned', 'platform')},
            },
        ),
    ]
