# Generated by Django 4.1.3 on 2022-11-28 09:01

import cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cards_delete_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='account_assigned',
            field=models.EmailField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='cvv_number',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[cards.validators.clean_cvv_number]),
        ),
        migrations.AlterField(
            model_name='cards',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[cards.validators.clean_expiration_date]),
        ),
        migrations.AlterField(
            model_name='cards',
            name='in_tickets_com',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cards',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cards',
            name='parent_card',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
