# Generated by Django 4.1.3 on 2022-11-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_cards_account_assigned_alter_cards_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
