# Generated by Django 4.1.3 on 2022-11-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_cards_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
