# Generated by Django 4.1.3 on 2022-11-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cards_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
