# Generated by Django 4.1.3 on 2022-11-30 05:09

import cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_cards_created_at_alter_cards_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='account_assigned',
            field=models.EmailField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cards',
            name='address',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_number',
            field=models.CharField(max_length=16, validators=[cards.validators.clean_card_number]),
        ),
        migrations.AlterField(
            model_name='cards',
            name='city',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='cards',
            name='created_by',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cards',
            name='cvv_number',
            field=models.CharField(max_length=4, validators=[cards.validators.clean_cvv_number]),
        ),
        migrations.AlterField(
            model_name='cards',
            name='expiration_date',
            field=models.CharField(max_length=5, validators=[cards.validators.clean_expiration_date]),
        ),
        migrations.AlterField(
            model_name='cards',
            name='in_tm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cards',
            name='parent_card',
            field=models.CharField(default='NA', max_length=150),
        ),
        migrations.AlterField(
            model_name='cards',
            name='platform',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='cards',
            name='state',
            field=models.CharField(default='NA', max_length=2, validators=[cards.validators.clean_state]),
        ),
        migrations.AlterField(
            model_name='cards',
            name='team',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cards',
            name='type',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='cards',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='zip_code',
            field=models.CharField(default='NA', max_length=5, validators=[cards.validators.clean_zip_code]),
        ),
    ]
