# Generated by Django 4.1.3 on 2022-11-30 05:21

import cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_cards_address_alter_cards_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cards',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cards',
            name='created_by',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cards',
            name='parent_card',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cards',
            name='platform',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cards',
            name='state',
            field=models.CharField(max_length=2, validators=[cards.validators.clean_state]),
        ),
        migrations.AlterField(
            model_name='cards',
            name='team',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cards',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cards',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[cards.validators.clean_zip_code]),
        ),
    ]
