# Generated by Django 4.1.3 on 2022-12-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_cards_address_alter_cards_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'ordering': ['-created_at'], 'permissions': (('import_cards', 'Can import'), ('export_cards', 'Can export')), 'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
    ]
