# Generated by Django 4.1.3 on 2022-12-06 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0010_alter_cards_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_cards_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
