# Generated by Django 4.1.3 on 2022-12-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_cards_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='specific_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
