# Generated by Django 4.1.3 on 2022-12-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_cards_specific_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='primary_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
