# Generated by Django 4.1.3 on 2022-12-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_cards_primary_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='primary_password',
        ),
    ]
