# Generated by Django 4.1.3 on 2022-12-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_remove_cards_primary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='specific_team',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
