# Generated by Django 4.1.3 on 2022-12-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_alter_cards_specific_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='specific_team',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
