# Generated by Django 4.1.3 on 2022-12-07 05:56

import cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_alter_cards_specific_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='parent_card',
            field=models.CharField(max_length=150, validators=[cards.validators.any_or_na]),
        ),
        migrations.AlterField(
            model_name='cards',
            name='specific_team',
            field=models.CharField(max_length=100, validators=[cards.validators.any_or_na]),
        ),
    ]
