name: Deployment Notification

on:
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "🚀 *Deployment Completed*: the app has been deployed to Azure Web App\n*Environment:* production\n*Deployed by:* ${{ github.actor }}\n*Commit:* ${{ github.sha }}"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
