name: Deployment Notification

on:
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        if: success()
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": ":rocket: *Deployment Completed*: the app has been deployed to Azure Web App\n*Environment:* production\n*Deployed by:* ${{ github.actor }}\n*Commit:* <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|'"$SHORT_SHA"'>"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
