name: Deployment Notification

on:
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        if: success()
        run: |
          COMMIT_SHA=${{ github.event.inputs.deployed_commit || github.sha }}
          SHORT_SHA=$(echo $COMMIT_SHA | cut -c1-7)
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          WORKFLOW_FILE=$(echo "${{ github.workflow_ref }}" | sed 's|.*/||')
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": ":rocket: *Deployment Completed*: '"$REPO_NAME"' has been deployed to Azure Web App\n*Environment:* production\n*Workflow file:* '"$WORKFLOW_FILE"'\n*Deployed by:* ${{ github.actor }}\n*Commit:* <https://github.com/${{ github.repository }}/commit/'"$COMMIT_SHA"'|'"$SHORT_SHA"'>"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
