name: Deployment Notification

on:
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":rocket: *Deployment Completed*: the app has been deployed to Azure Web App"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Environment:*\nproduction"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Deployed by:*\n${{ github.actor }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha | slice(0, 7) }}>"
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
