name: Python Linter with Ruff

on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Ruff
        uses: chartboost/ruff-action@v1

  notify_ruff_results:
    runs-on: ubuntu-latest
    needs: ruff
    if: ${{ always() }}
    steps:
      - name: Notify Ruff results on Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ needs.ruff.result }}
          fields: repo,commit,author,action,eventName,ref,workflow,job,took
          author_name: 8398a7@action-slack
          github_token: ${{ secrets.GH_PAT }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
