name: Python Linter

on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Ruff
        run: python -m pip install ruff
      - name: Check and Format with Ruff
        run: ruff format .
        continue-on-error: true
      - name: Commit changes
        if: ${{ steps.ruff.outputs.exit-code != '0' }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Apply Ruff code formatting"
      - name: Create Pull Request
        if: ${{ steps.ruff.outputs.exit-code != '0' }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PAT }}
          title: "Apply Ruff code formatting"
          commit-message: "Apply Ruff code formatting"
          body: "This pull request applies Ruff code formatting."
          base: ${{ github.head_ref }}
          branch: "ruff/format-${{ github.head_ref }}"
      - name: Notify Ruff outcome on Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,action,eventName,ref,workflow,job,took
          author_name: 8398a7@action-slack
          github_token: ${{ secrets.GH_PAT }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
