name: Python Linter

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - run: pip install ruff
    - run: |
       ruff check . --config django-backend/pyproject.toml
       ruff format .  --config django-backend/pyproject.toml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'style: fix styling issues using ruff'
