name: Python Linter

on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install isort
        run: python -m pip install isort

      - name: Run isort
        run: isort

      - name: Install Ruff
        run: python -m pip install ruff

      - name: Check and Format with Ruff
        id: ruff_format
        run: |
          ruff format .
          echo "RUFF_CHANGES=$(git status --porcelain | wc -l)" >> $GITHUB_ENV

      - name: Commit changes
        if: env.RUFF_CHANGES > 0
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Apply Ruff code formatting"
          git push origin ${{ github.head_ref }}

      - name: Notify Ruff outcome on Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,action,eventName,ref,workflow,job,took
          author_name: 8398a7@action-slack
          github_token: ${{ secrets.GH_PAT }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
